#pragma once

#include <map>

#include "../BotProfiles/CompositeBot.hpp"
#include "../CoreEngine/GameState.hpp"
#include "BayesianTracker.hpp"
#include "Range.hpp"

namespace PokerEngine {
    namespace AI {

        /**
         * @class InferenceEngine
         * @brief Evaluates logic bridging game state and AI profiles, combining
         * EV maximization and GTO profiles.
         *
         * Unifies raw mathematical probabilities generated by the Monte Carlo
         * simulators with Bayesian opponent behavioral profiling to accurately
         * balance standard GTO tendencies with direct exploit optimizations.
         */
        class InferenceEngine {
        public:
            /**
             * @brief Decides the optimal action for a given bot.
             * @param state The current table context.
             * @param botPlayerId Intended bot player.
             * @param profile The instantiated behavioral profile.
             * @param currentOpponentRanges Estimated probability mappings for
             * opposing hands.
             * @param tracker Optional tracker providing real-time Bayesian
             * profiling of opponents.
             * @return Legal action derived from EV mathematics and the
             * profile's instructions.
             */
            static PlayerAction decideAction(
                const Engine::GameState& state, int botPlayerId,
                CompositeBot& profile,
                const std::map<int, Range>& currentOpponentRanges,
                const BayesianTracker* tracker = nullptr);
        };

    }  // namespace AI
}  // namespace PokerEngine
